using FL_Test_2.Repository.Entities;
using Microsoft.EntityFrameworkCore;

namespace FL_Test_2.Repository;

public class AppDbContext : DbContext
{
    public AppDbContext(DbContextOptions<AppDbContext> options) : base(options)
    {
        Database.EnsureCreated();
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        // Generated by hands because of check up goal.
        modelBuilder.Entity<User>().HasData(
            new User { UserId = new Guid("0afa834e-ce99-4613-ac2c-c5b90268bc16"), Domain = "IT", Name = "Igor" },
            new User { UserId = new Guid("94ece4bb-8d83-40a2-b160-f99aca926c63"), Domain = "Energy", Name = "Egor" },
            new User { UserId = new Guid("89ec9bb3-5d69-4d59-9ab8-6397d01dd924"), Domain = "IT", Name = "Andrew" },
            new User { UserId = new Guid("489dc64f-7f85-4c29-865a-d0da398580bb"), Domain = "Finance", Name = "Alexey" },
            new User { UserId = new Guid("9b034c19-6053-421a-9718-ec726491a3f0"), Domain = "Energy", Name = "Dima" },
            new User { UserId = new Guid("a4c4bd5e-1199-438e-bd3e-ee704bd91ee8"), Domain = "Finance", Name = "Kesha" },
            new User { UserId = new Guid("7f69f7fd-ac56-433f-9e39-0f77bec671ce"), Domain = "Finance", Name = "Inokentey" },
            new User { UserId = new Guid("ab7d973b-1fbd-469f-b915-bb7b21ef117f"), Domain = "Energy", Name = "Evgeniy" },
            new User { UserId = new Guid("a0954fff-5499-4ffb-a5e7-bfa2fa198926"), Domain = "IT 2", Name = "Alexander" },
            new User { UserId = new Guid("984328f4-74a6-43e6-9c21-16bf2fcad6b8"), Domain = "IT 2", Name = "Vladimir" },
            new User { UserId = new Guid("bec0804c-4961-47dc-981d-4774b43c4723"), Domain = "IT", Name = "Daniil" },
            new User { UserId = new Guid("3836b38d-540b-408f-81e1-39033fca42e9"), Domain = "IT", Name = "Artem" },
            new User { UserId = new Guid("138c86c1-50e3-46ec-bcf4-de758d1246c2"), Domain = "IT", Name = "Pavel" },
            new User { UserId = new Guid("f42f2eef-860b-48cd-9d35-2958f4be037e"), Domain = "IT", Name = "Valim" },
            new User { UserId = new Guid("91caf1f0-e030-4c3e-a4a9-3d6a96bd0df0"), Domain = "IT", Name = "Sergey" }
        );

        modelBuilder.Entity<Tag>().HasData(
            new Tag { TagId = new Guid("3786a26c-7236-4f89-95cc-554525aa8249"), Domain = "IT", Value = "FirstTag" },
            new Tag { TagId = new Guid("fbed4178-2a2e-47b5-a3ed-2fa3e3c03d32"), Domain = "Energy", Value = "SecondTag" },
            new Tag { TagId = new Guid("d0a01a5f-d484-4ee6-9dd8-d2f5072a1ec4"), Domain = "IT 2", Value = "ThirdTag" },
            new Tag { TagId = new Guid("55cf219a-2c88-4b9f-b1d4-5463727eb75e"), Domain = "Finance", Value = "FouthTag" }
        );

        modelBuilder.Entity<TagToUser>().HasData(
            new TagToUser { TagId = new Guid("3786a26c-7236-4f89-95cc-554525aa8249"), UserId = new Guid("0afa834e-ce99-4613-ac2c-c5b90268bc16"), EntityId = new Guid("c7f4f7bd-d114-407c-974b-81d4cc7ae2d6") }, // IT
            new TagToUser { TagId = new Guid("fbed4178-2a2e-47b5-a3ed-2fa3e3c03d32"), UserId = new Guid("94ece4bb-8d83-40a2-b160-f99aca926c63"), EntityId = new Guid("4e2a3f8a-d8f7-4840-b050-c90afe731d2c") }, // Energy
            new TagToUser { TagId = new Guid("d0a01a5f-d484-4ee6-9dd8-d2f5072a1ec4"), UserId = new Guid("984328f4-74a6-43e6-9c21-16bf2fcad6b8"), EntityId = new Guid("e8a9680e-9587-4a65-a661-4841d83f347e") }, // IT 2
            new TagToUser { TagId = new Guid("55cf219a-2c88-4b9f-b1d4-5463727eb75e"), UserId = new Guid("94ece4bb-8d83-40a2-b160-f99aca926c63"), EntityId = new Guid("fbafc82c-4032-4813-9632-3da2ebf91efc") }, // Energy
            new TagToUser { TagId = new Guid("d0a01a5f-d484-4ee6-9dd8-d2f5072a1ec4"), UserId = new Guid("984328f4-74a6-43e6-9c21-16bf2fcad6b8"), EntityId = new Guid("a8cec4d6-869e-4c8a-b699-8880e471fdee") }, // IT 2
            new TagToUser { TagId = new Guid("55cf219a-2c88-4b9f-b1d4-5463727eb75e"), UserId = new Guid("94ece4bb-8d83-40a2-b160-f99aca926c63"), EntityId = new Guid("1bda44d8-aff6-4841-85cd-23411687ddf9") }, // Energy
            new TagToUser { TagId = new Guid("d0a01a5f-d484-4ee6-9dd8-d2f5072a1ec4"), UserId = new Guid("984328f4-74a6-43e6-9c21-16bf2fcad6b8"), EntityId = new Guid("8789a7d5-7f04-4132-8966-b885c0586648") }, // IT 2
            new TagToUser { TagId = new Guid("3786a26c-7236-4f89-95cc-554525aa8249"), UserId = new Guid("3786a26c-7236-4f89-95cc-554525aa8249"), EntityId = new Guid("1a37dd65-dec7-4981-8f36-81326fd4701d") }, // IT
            new TagToUser { TagId = new Guid("3786a26c-7236-4f89-95cc-554525aa8249"), UserId = new Guid("3786a26c-7236-4f89-95cc-554525aa8249"), EntityId = new Guid("b0bac326-b3ef-4dde-9867-9ccd9755e354") }, // IT
            new TagToUser { TagId = new Guid("d0a01a5f-d484-4ee6-9dd8-d2f5072a1ec4"), UserId = new Guid("a0954fff-5499-4ffb-a5e7-bfa2fa198926"), EntityId = new Guid("a142ad30-aa4c-4a83-833f-badb434e6e4e") }, // IT 2
            new TagToUser { TagId = new Guid("d0a01a5f-d484-4ee6-9dd8-d2f5072a1ec4"), UserId = new Guid("a0954fff-5499-4ffb-a5e7-bfa2fa198926"), EntityId = new Guid("d0a01a5f-d484-4ee6-9dd8-d2f5072a1ec4") }, // IT 2
            new TagToUser { TagId = new Guid("fbed4178-2a2e-47b5-a3ed-2fa3e3c03d32"), UserId = new Guid("9b034c19-6053-421a-9718-ec726491a3f0"), EntityId = new Guid("8a81e9e0-a2d2-4484-bee9-7a7556b5f7a5") }, // Energy
            new TagToUser { TagId = new Guid("fbed4178-2a2e-47b5-a3ed-2fa3e3c03d32"), UserId = new Guid("9b034c19-6053-421a-9718-ec726491a3f0"), EntityId = new Guid("e60be0c5-e2a2-467d-9cd4-c97d4f2fa212") }, // Energy
            new TagToUser { TagId = new Guid("fbed4178-2a2e-47b5-a3ed-2fa3e3c03d32"), UserId = new Guid("ab7d973b-1fbd-469f-b915-bb7b21ef117f"), EntityId = new Guid("e21c5c1e-2930-4baa-a885-a69b64c76f26") }, // Energy
            new TagToUser { TagId = new Guid("fbed4178-2a2e-47b5-a3ed-2fa3e3c03d32"), UserId = new Guid("ab7d973b-1fbd-469f-b915-bb7b21ef117f"), EntityId = new Guid("ba6a2199-b728-4fdf-b450-02fa23ee76dc") }, // Energy
            new TagToUser { TagId = new Guid("55cf219a-2c88-4b9f-b1d4-5463727eb75e"), UserId = new Guid("489dc64f-7f85-4c29-865a-d0da398580bb"), EntityId = new Guid("6a786784-ebd3-4004-89e7-dd22e7f29b55") }, // Finance
            new TagToUser { TagId = new Guid("55cf219a-2c88-4b9f-b1d4-5463727eb75e"), UserId = new Guid("489dc64f-7f85-4c29-865a-d0da398580bb"), EntityId = new Guid("a9f18eb9-117a-4814-a4a2-0102c26a49e7") }, // Finance
            new TagToUser { TagId = new Guid("55cf219a-2c88-4b9f-b1d4-5463727eb75e"), UserId = new Guid("489dc64f-7f85-4c29-865a-d0da398580bb"), EntityId = new Guid("14dfb07b-3ee5-4a7c-898c-58399c93bd11") }, // Finance
            new TagToUser { TagId = new Guid("55cf219a-2c88-4b9f-b1d4-5463727eb75e"), UserId = new Guid("a4c4bd5e-1199-438e-bd3e-ee704bd91ee8"), EntityId = new Guid("9e5d8ee9-932f-401b-b7f1-60cfff547103") }, // Finance
            new TagToUser { TagId = new Guid("55cf219a-2c88-4b9f-b1d4-5463727eb75e"), UserId = new Guid("a4c4bd5e-1199-438e-bd3e-ee704bd91ee8"), EntityId = new Guid("e14c7398-de4e-461e-ab14-94319eb279f4") }, // Finance
            new TagToUser { TagId = new Guid("55cf219a-2c88-4b9f-b1d4-5463727eb75e"), UserId = new Guid("7f69f7fd-ac56-433f-9e39-0f77bec671ce"), EntityId = new Guid("d3ce182b-5875-4cc2-8e83-697c27a894f6") }, // Finance
            new TagToUser { TagId = new Guid("3786a26c-7236-4f89-95cc-554525aa8249"), UserId = new Guid("3836b38d-540b-408f-81e1-39033fca42e9"), EntityId = new Guid("b765e55f-d78f-4b9d-a75c-259658229843") }, // IT
            new TagToUser { TagId = new Guid("3786a26c-7236-4f89-95cc-554525aa8249"), UserId = new Guid("138c86c1-50e3-46ec-bcf4-de758d1246c2"), EntityId = new Guid("adeaf3aa-6b53-4505-8231-38fa06cb9545") }, // IT
            new TagToUser { TagId = new Guid("3786a26c-7236-4f89-95cc-554525aa8249"), UserId = new Guid("f42f2eef-860b-48cd-9d35-2958f4be037e"), EntityId = new Guid("a564c359-1d9d-43e3-ae2c-c6ec4adb2057") }, // IT
            new TagToUser { TagId = new Guid("d0a01a5f-d484-4ee6-9dd8-d2f5072a1ec4"), UserId = new Guid("a0954fff-5499-4ffb-a5e7-bfa2fa198926"), EntityId = new Guid("04772831-1992-411e-a135-b6c43fd234f7") }, // IT 2
            new TagToUser { TagId = new Guid("d0a01a5f-d484-4ee6-9dd8-d2f5072a1ec4"), UserId = new Guid("89ec9bb3-5d69-4d59-9ab8-6397d01dd924"), EntityId = new Guid("e59b91c1-43d8-4d26-844b-ba35641d19d0") }, // IT 2
            new TagToUser { TagId = new Guid("d0a01a5f-d484-4ee6-9dd8-d2f5072a1ec4"), UserId = new Guid("a0954fff-5499-4ffb-a5e7-bfa2fa198926"), EntityId = new Guid("86faea54-f224-4437-b273-cea11ed5cb76") }, // IT 2
            new TagToUser { TagId = new Guid("3786a26c-7236-4f89-95cc-554525aa8249"), UserId = new Guid("91caf1f0-e030-4c3e-a4a9-3d6a96bd0df0"), EntityId = new Guid("d9a59386-f13b-4d4f-a8df-7a6deff92936") }  // IT
        );
    }

    public DbSet<User> Users { get; set; }
    public DbSet<Tag> Tags { get; set; }
    public DbSet<TagToUser> TagsToUsers { get; set; }
}
